open_collective: pilotezebs
custom: github.com/NGcodeX
github: NGUENAZEBS
patreon: #encours
ko_fi: pilotezebs
tidelift: # npm/JAVA
community_bridge: NGcodeX
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
